[metadata]
# This includes the license file(s) in the wheel.
# https://wheel.readthedocs.io/en/stable/user_guide.html#including-license-files-in-the-generated-wheel-file
license_files = LICENSE.txt

[versioneer]
VCS = git
style = pep440
versionfile_source = src/quantkit/_version.py
versionfile_build = quantkit/_version.py
tag_prefix = v
parentdir_prefix = quantkit-

[tool:pytest]
minversion = 4.0.2
testpaths = quantkit


[coverage:run]
branch = True
source = src
omit=
    tests/*,
    **/*/_version.py
    **/*/__init__.py,

# http://flake8.pycqa.org/en/2.6.0/warnings.html#error-codes
# https://pycodestyle.readthedocs.io/en/latest/intro.html#error-codes

[flake8]
docstring_style=numpy
ignore =
    E226,
    E302,
    E41,
    WPS412,
    WPS609,
    Q,
    D202,
    WPS362,
    WPS331,
    WPS442, # Found outer scope names shadowing: returns
per-file-ignores =
    __init__.py:WPS300,WPS410,WPS436,WPS42
    setup.py:D100
exclude =
    .git,
    .tox,
    .undodir,
    .pytest_cache,
    tests,
    docs,
    versioneer.py,
    src/quantkit/_version.py,
max-line-length = 79
max-complexity = 10
